name: Build XenHe Linux ISO

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: '测试'
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged  # 需要特权模式用于archiso构建

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: chriskmanx/qmole-packages

    - name: Initialize system
      run: |
        # 创建普通用户
        useradd -m -G wheel -s /bin/bash builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
        # 初始化密钥环
        sudo -u builder pacman-key --init
        sudo -u builder pacman-key --populate archlinux

    - name: Install dependencies
      run: |
        # 使用普通用户安装系统依赖
        sudo -u builder sudo pacman -Sy --noconfirm archiso reflector git base-devel
        
        # 安装aurutils
        sudo -u builder git clone https://aur.archlinux.org/aurutils.git
        cd aurutils
        sudo -u builder makepkg -si --noconfirm
        cd ..
        
        # 创建必要的用户组
        groupadd -f alpm
        usermod -aG alpm builder

    - name: Make build script executable
      run: chmod +x build.bash

    - name: Run build script
      run: |
        # 切换用户执行构建脚本
        sudo -u builder ./build.bash --noconfirm

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: xenhe-linux-iso
        path: target/*.iso
        retention-days: 5